name: Trigger PR in dhis2-core with contracts from PR in dhis2-api-contracts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-core-pr-with-updated-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dhis2-api-contracts PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: api-contracts

      - name: Checkout dhis2-core
        uses: actions/checkout@v4
        with:
          repository: dhis2/dhis2-core
          token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
          path: dhis2-core
            
      - name: Prepare GnuPG directory
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          touch ~/.gnupg/gpg.conf
          touch ~/.gnupg/gpg-agent.conf
          
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        
          gpgconf --kill gpg-agent

      - name: Import GPG private key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" > key.asc
          
          gpg --batch --yes \
              --pinentry-mode loopback \
              --passphrase "${{ secrets.PGP_PASSPHRASE }}" \
              --import key.asc
          
      - name: Get GPG key ID
        id: gpg
        run: |
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ {print $5; exit}')
          echo "KEY_ID=$KEY_ID" >> "$GITHUB_OUTPUT"

      - name: Configure Git to sign commits
        run: |
          git config --global user.name "dhis2-bot"
          git config --global user.email "apps@dhis2.org"
          git config --global user.signingkey "${{ steps.gpg.outputs.KEY_ID }}"
          git config --global commit.gpgsign true
          git config --global gpg.program gpg

      - name: Copy dhis2-api-contracts PR contracts to dhis2-core
        run: |
          cp -r api-contracts/contracts/ dhis2-core/dhis-2/dhis-test-web-api/src/test/resources/

      - name: Create PR in dhis2-core with updated contracts
        run: |
          cd dhis2-core
          git checkout -b "sync-from-api-contracts-pr-${{ github.event.number }}"
          git add .
          git -c gpg.program=gpg \
              -c gpg.format=openpgp \
              -c commit.gpgsign=true \
              -c gpg.passphrase="${{ secrets.BOT_GPG_PASSPHRASE }}" \ 
              commit -S -m "Sync from api-contracts PR ${{ github.event.pull_request.html_url }}"
              git push origin "sync-from-api-contracts-pr-${{ github.event.number }}"
          
          gh pr create --title "Sync contracts from api-contracts PR ${{ github.event.pull_request.html_url }}" \
                       --body "Auto-generated from api-contracts PR: ${{ github.event.pull_request.html_url }}
          ## Changes
          This PR automatically syncs contract changes from the api-contracts repository.
          ## Review Notes
          Please review the contract changes and ensure the the following test passes before merging:
          \`dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/contract/ApiContractTest.java\`" \
                       --head "sync-from-api-contracts-pr-${{ github.event.number }}" \
                       --base master
        env:
          GITHUB_TOKEN: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          GPG_TTY: /dev/tty